### ISSUE TITLE
✨[인증] 구독 페이지 인증 받는 법

### ISSUE THREAD

**Issue by yoorym-kim** [PrograMemo-Groom/youtube-clone#118]
<초기 상태>

![image](https://github.com/user-attachments/assets/a4d6470e-c7a5-49ae-9368-9d5d8e6b4b3d)

여러분 google cloud의 현상태는 이렇게 되어있을겁니다
api키, OAuth는 지금 이대로 .env 파일에 있는거 그대로 쓰시면 됩니다

!!! 저한테 이 OAouth가 있는 구글 이메일을 보내주세요 !!!!

그러면 테스트 사용자로 추가해두겠습니다

<추가로 하셔야 할 사항>

![image](https://github.com/user-attachments/assets/5d5dacbb-50e9-40bc-aecc-721a688e171e)

여기에 자기 이메일 입력, 저장하기
그러면 테스트 사용자가 1로 변한걸 볼 수 있어요
(이미 자기 이메일이 테스트 사용자로 등록된 분은 할 필요 x)

![image](https://github.com/user-attachments/assets/d84ea546-e8df-4e8e-b015-00d32f2e2348)
![image](https://github.com/user-attachments/assets/07f625d3-fd37-4348-8301-dc4350f6f79a)

이 버튼을 눌러서 앱을 게시 상태로 체크합니다
아래로 내려보았을 때 여전히 아까 추가한 사용자는 1로 떠있어야 합니다

이러면 구글 OAouth 설정 끝.

<우리 앱에서 구독 탭을 엽니다>

처음에는 상단 버튼 3개만 뜨고,  페이지에 아무영상도 안 뜹니다
상단 첫번째 버튼(token 발급) 클릭.

![image](https://github.com/user-attachments/assets/26655537-0a6e-4d50-b6a1-cca370aed75b)

이런 창이 뜹니다
제게 주신 e-mail주소(여러분이 OAuth 설정한)의 계정을 클릭.

![image](https://github.com/user-attachments/assets/8a2835f6-2b7f-402e-a775-f37bc68e079e)

계속 클릭.

![image](https://github.com/user-attachments/assets/f5306378-7480-453b-be0d-3cc14cc77196)

계속 클릭. (튕기면 다시 토큰발급 버튼 눌러서 반복해주세요)

![image](https://github.com/user-attachments/assets/fc06bb7e-f798-452e-8acf-05d9f3878ae6)

왼쪽 하단 '고급' 누르고 '~(프로젝트명)~로 이동' 클릭.

끝!!

데이터가 화면에 뜹니당
안 뜬다면 인증까지 시간이 걸려서일수도 있고,
토큰 발급 버튼 다시 누르고 과정 반복하고 화면의 2번째 버튼(누르면 데이터 가져와)를 누르면 뜹니다

혹시 안된다면 말씀 부탁드립니다 :)

**Comment by Saaad9** [comment]
ehdgbstla@gmail.com 입니당

**Comment by jdaily00** [comment]
jkh40581@gmail.com 입니당

**Comment by happygirlll** [comment]
lbm000314@gmail.com이랑 lbm0314@yu.ac.kr로 부탁드려요 !!
