### ISSUE TITLE
[깃허브 이슈] 이슈 등록하면 discord로 개인 알람 설정

### ISSUE THREAD

**Issue by newfly101** [PrograMemo-Groom/youtube-clone#64]
![image](https://github.com/user-attachments/assets/9d07f3ce-22d9-4c64-859e-5de74a7cf9b6)

각자 개인 채널 생성해뒀습니다.
이슈 관련 사항으로 본인이 필요한 것들만 알림 받을 수 있는 채널이 생겼습니다.

이슈에 할당되는 사람에게로 github hooks 이용해서 날아갑니다.
![image](https://github.com/user-attachments/assets/e95db96e-2190-4951-888c-af014652be65)

할당된 이슈에 댓글이 달리면 또 메세지 날아옵니다
![image](https://github.com/user-attachments/assets/9e98f64f-b8c3-4ee4-8a1d-3dfa5176a135)

**Comment by newfly101** [comment]
확인

**Comment by Saaad9** [comment]
야무집니다

**Comment by newfly101** [comment]
정상 동작 체크
